### ISSUE TITLE
Table Prefix is automatically added if there very amigous columns, even if the amigious columns removed by an explicit SELECT

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#373]
I have the following query:

`select 	
	    species.name as "name",
	    species.id as speciesid,
		count(*) animals
	    from contacttoanimal
	    left join animal on animal.id=contactto
	    left join breed ON breed.id = animal.fk_breed
	    left join species on species.id = breed.fk_species
		where contactfrom=${clientId}
		group by species.name, species.id`
		
where the tables animal, breed and specias all have the column "name" - i guess this is the reason why the table prefix is added in the result:

`[
  {
    "species.name": "Sheep",
    "value": 2,
    "animals": 16
  },
  {
    "species.name": "Goat",
    "value": 3,
    "animals": 71
  }
]`		

So although in the resultset there are no duplicates anymore (becasue the select clause only selects the name of species), in the resultset the prefix "species." is added. Even if you add an 'as "name"' or surround it with a WITH statement, the prefix is always added.

But because e.g. for the selection of an input field, the property "name" (without prefix) is needed, i need a function to remove the prefix after executing the query.

So it would be good if the prefix is only added if the result really has duplicates (e.g. if i add the column name of species and breed)

**Comment by aeberhart** [comment]
This is a bit trick to fix, because we cannot distinguish between "select name" and "select name as name" in the result metadata.

Here are two workarounds:

* you can do some computation (e.g. append an empty string) in the select clause and then apply "as name" 
![image](https://github.com/dashjoin/platform/assets/61732435/583c9638-5c56-410a-8264-5ed4bd2b4447)

* you can use JSONata to transform the result 
![image](https://github.com/dashjoin/platform/assets/61732435/4ca9284c-5d5d-471d-bcd2-1eda2acfb991)

**Comment by pgrill79** [comment]
Hi @aeberhart  - thanks - i bult me a workaround where i wrote a generic transform function, where i can do a search replace in the keys:
`$call("json_replaceKey", {"data":$data,"search": "species.", "new":"" });`
