### ISSUE TITLE
Automatic refresh "disturbs" user input when typing fast

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#374]
I have an input field and in to the Input description i wanted to add the text:

"Enter the species you want to display"

But it seems that after every Keypress a Refresh is done, and if you are typing fast, inputs are swallowd:

![image](https://github.com/dashjoin/platform/assets/47058152/d88c00f3-f2ed-4106-bdf7-02afa16cf2c3)

Only if you are typing very slow (or do a copy paste) it works fine.

**Comment by aeberhart** [comment]
I couldn't reproduce the issue (tried with master, 5.1, both using localhost and cloud). In 5.2, we fixed an issue that might be the root cause.

Some questions:

* does this happen all the time or just in conjunction with other widgets present on the page
* which page parts get redrawn?
* if other widgets are present, what kind of widget and what kind of query is run?

**Comment by pgrill79** [comment]
Can confirm that it does not happen with 5.1.30
