### ISSUE TITLE
Filter in Action Table for Date columns does not work

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#378]
If an actino table has a date column and you add a filter, no input is accepted:

![image](https://github.com/dashjoin/platform/assets/47058152/75e2aa77-10e9-4257-90d7-a05d0641e5db)

You can type in something in the field but if you leave the field it is cleared again and also nithing is filterd

**Comment by aeberhart** [comment]
In order to avoid the table being empty as you type (since we filter on equality and not "startsWith"), we switched the filters to SelectInput (https://marmelab.com/react-admin/SelectInput.html).

This input allows you to enter a sub-string and it then shows the options. If the component loses focus (e.g. by hitting TAB), the sub-string is discarded.

You have to select one of the options in the dropdown in order for the filter to be set.

Does this solve your issue?

**Comment by pgrill79** [comment]
Yes, understood - i havent selected the value in the select box... after selecting the value in the drop down it works.
