### ISSUE TITLE
Set default "Rows per page" for Action table

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#380]
We use many Action tables and Tables and most of the time we want to show more than 10 rows per page (which is the default).

So it would be great to have the possiblity to set a default "Rows per page" for each action table or that this value is stored permanently.

**Comment by aeberhart** [comment]
The sort order, filters and rows to display are stored in the local storage (visible in the dev console / Application). A sample key is:

```
RaStore.preferences.$gitStatus().{"type":type, "path":path, "diff": diff}5.listParams = 
{"filterValues":{},"sort":{"field":"diff","order":"ASC"},"perPage":50}
```

As the key, we chose the jsonata expression appended with the result length. This reason for that is to make sure the table is updated when an entry is deleted.

This has the negative side effect, that the settings are lost if the row count changes for other reasons.

We need to come up with another way of handling updates while not including the result count in the resource key

**Comment by aeberhart** [comment]
guess this issue #363 is also related

both tables get the ConstDataProvider with the same ID ($ call("fn")). The fact that they have different arguments makes no difference when computing the resource

**Comment by aeberhart** [comment]
The table and actionTable widget now support a "perPage" settings which can be 5, 10, 25 or 50
The logic is as follows:
* the first time the user visits the page, perPage is the widget's setting or 10 otherwise
* if the user changes the setting, the new value is placed into the browser's localstorage and that value is used from there on
* when testing, make sure you open a private browsing page
