### ISSUE TITLE
CSV Export from table does not take column selection into account - also PKs are not resolved in the Export

### ISSUE THREAD

**Issue by pgrill79** [dashjoin/platform#385]
I can export an table to a CSV.  A filter is taken into account, but

- the selected columns are not (all columns are exported)
-  also PKs are not resolved in the Export

Table (with Filter an selected columns):
![image](https://github.com/dashjoin/platform/assets/47058152/86d12cd7-8e0a-47f7-a881-9a9deb9f558b)

Export:
![image](https://github.com/dashjoin/platform/assets/47058152/115944fa-613a-4dfe-8215-4e247d777dbe)

**Comment by aeberhart** [comment]
we are using the default react admin export feature
https://marmelab.com/react-admin/List.html#exporter

guess taking the projected columns into account would be possible

not sure about the key issue, since there might be different keys that resolve to the same key (e.g. many persons might be called fisher)

**Comment by aeberhart** [comment]
opened an issue with react admin:
https://github.com/marmelab/react-admin/issues/9986

**Comment by aeberhart** [comment]
We decided to stick with the default logic offered by the underlying framework.
There are simply too many export options which make it quite complex.

As a workaround, you can create a query that resolves the pks and formats the other options as needed
